// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/components/lens_distortion.def.rs".

#pragma once

#include "../encodings/lens_distortion.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Parametric lens distortion of a pinhole camera, in OpenCV coefficient ordering.
    ///
    /// When attached to a `archetypes::Pinhole`, the viewer rectifies (undistorts) images
    /// shown under that camera so that the linear `image_from_camera` projection maps
    /// 3D geometry onto the correct pixels.
    struct LensDistortion {
        rerun::encodings::LensDistortion distortion;

      public:
        LensDistortion() = default;

        LensDistortion(rerun::encodings::LensDistortion distortion_) : distortion(distortion_) {}

        LensDistortion& operator=(rerun::encodings::LensDistortion distortion_) {
            distortion = distortion_;
            return *this;
        }

        /// Cast to the underlying LensDistortion encoding
        operator rerun::encodings::LensDistortion() const {
            return distortion;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::encodings::LensDistortion) == sizeof(components::LensDistortion));

    /// \private
    template <>
    struct Loggable<components::LensDistortion> {
        static constexpr std::string_view ComponentType = "rerun.components.LensDistortion";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type() {
            return Loggable<rerun::encodings::LensDistortion>::arrow_data_type();
        }

        /// Serializes an array of `rerun::components::LensDistortion` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::LensDistortion* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::encodings::LensDistortion>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::encodings::LensDistortion>::to_arrow(
                    &instances->distortion,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
