// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/components/lens_distortion.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Component**: Parametric lens distortion of a pinhole camera, in OpenCV coefficient ordering.
///
/// When attached to a [`archetypes::Pinhole`][crate::archetypes::Pinhole], the viewer rectifies (undistorts) images
/// shown under that camera so that the linear `image_from_camera` projection maps
/// 3D geometry onto the correct pixels.
#[derive(Clone, Debug, Copy, PartialEq, ::re_byte_size::SizeBytes)]
pub struct LensDistortion(pub crate::encodings::LensDistortion);

impl ::re_types_core::WrapperComponent for LensDistortion {
    type Encoding = crate::encodings::LensDistortion;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.LensDistortion".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Encoding {
        self.0
    }
}

::re_types_core::macros::impl_into_cow!(LensDistortion);

impl<T: Into<crate::encodings::LensDistortion>> From<T> for LensDistortion {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::encodings::LensDistortion> for LensDistortion {
    #[inline]
    fn borrow(&self) -> &crate::encodings::LensDistortion {
        &self.0
    }
}

impl std::ops::Deref for LensDistortion {
    type Target = crate::encodings::LensDistortion;

    #[inline]
    fn deref(&self) -> &crate::encodings::LensDistortion {
        &self.0
    }
}

impl std::ops::DerefMut for LensDistortion {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::encodings::LensDistortion {
        &mut self.0
    }
}
