// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/lens_distortion_model.def.rs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class UInt8Type;
    using UInt8Builder = NumericBuilder<UInt8Type>;
} // namespace arrow

namespace rerun::encodings {
    /// **Encoding**: The parametric camera lens distortion model that a set of distortion coefficients belongs to.
    ///
    /// The model names and coefficient ordering follow the OpenCV calibration conventions,
    /// which are also used by ROS (`sensor_msgs/CameraInfo`).
    enum class LensDistortionModel : uint8_t {

        /// Radial + tangential distortion ("Brown-Conrady"), known as `plumb_bob` in ROS.
        ///
        /// Uses the coefficients `k1, k2, p1, p2, k3` (the remaining coefficients are ignored / zero).
        PlumbBob = 1,

        /// Rational polynomial distortion, known as `rational_polynomial` in ROS.
        ///
        /// Extends the plumb-bob model with a radial denominator polynomial, using all eight
        /// coefficients `k1, k2, p1, p2, k3, k4, k5, k6`.
        /// With `k4 = k5 = k6 = 0` this is identical to the plumb-bob model.
        RationalPolynomial = 2,
    };
} // namespace rerun::encodings

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<encodings::LensDistortionModel> {
        static constexpr std::string_view ComponentType = "rerun.encodings.LensDistortionModel";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::encodings::LensDistortionModel` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const encodings::LensDistortionModel* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::UInt8Builder* builder, const encodings::LensDistortionModel* elements,
            size_t num_elements
        );
    };
} // namespace rerun
