// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/lens_distortion.def.rs".

#include "lens_distortion.hpp"

#include "lens_distortion_model.hpp"

#include <arrow/builder.h>
#include <arrow/type_fwd.h>

namespace rerun::encodings {}

namespace rerun {
    const std::shared_ptr<arrow::DataType>& Loggable<encodings::LensDistortion>::arrow_data_type() {
        static const auto datatype = arrow::struct_({
            arrow::field(
                "model",
                Loggable<rerun::encodings::LensDistortionModel>::arrow_data_type(),
                false
            ),
            arrow::field(
                "coefficients",
                arrow::fixed_size_list(arrow::field("item", arrow::float64(), false), 8),
                false
            ),
        });
        return datatype;
    }

    Result<std::shared_ptr<arrow::Array>> Loggable<encodings::LensDistortion>::to_arrow(
        const encodings::LensDistortion* instances, size_t num_instances
    ) {
        // TODO(andreas): Allow configuring the memory pool.
        arrow::MemoryPool* pool = arrow::default_memory_pool();
        auto datatype = arrow_data_type();

        ARROW_ASSIGN_OR_RAISE(auto builder, arrow::MakeBuilder(datatype, pool))
        if (instances && num_instances > 0) {
            RR_RETURN_NOT_OK(Loggable<encodings::LensDistortion>::fill_arrow_array_builder(
                static_cast<arrow::StructBuilder*>(builder.get()),
                instances,
                num_instances
            ));
        }
        std::shared_ptr<arrow::Array> array;
        ARROW_RETURN_NOT_OK(builder->Finish(&array));
        return array;
    }

    rerun::Error Loggable<encodings::LensDistortion>::fill_arrow_array_builder(
        arrow::StructBuilder* builder, const encodings::LensDistortion* elements,
        size_t num_elements
    ) {
        if (builder == nullptr) {
            return rerun::Error(ErrorCode::UnexpectedNullArgument, "Passed array builder is null.");
        }
        if (elements == nullptr) {
            return rerun::Error(
                ErrorCode::UnexpectedNullArgument,
                "Cannot serialize null pointer to arrow array."
            );
        }

        {
            auto field_builder = static_cast<arrow::UInt8Builder*>(builder->field_builder(0));
            ARROW_RETURN_NOT_OK(field_builder->Reserve(static_cast<int64_t>(num_elements)));
            for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
                RR_RETURN_NOT_OK(
                    Loggable<rerun::encodings::LensDistortionModel>::fill_arrow_array_builder(
                        field_builder,
                        &elements[elem_idx].model,
                        1
                    )
                );
            }
        }
        {
            auto field_builder =
                static_cast<arrow::FixedSizeListBuilder*>(builder->field_builder(1));
            auto value_builder = static_cast<arrow::DoubleBuilder*>(field_builder->value_builder());

            ARROW_RETURN_NOT_OK(field_builder->AppendValues(static_cast<int64_t>(num_elements)));
            static_assert(sizeof(elements[0].coefficients) == sizeof(elements[0]));
            ARROW_RETURN_NOT_OK(value_builder->AppendValues(
                elements[0].coefficients.data(),
                static_cast<int64_t>(num_elements) * 8,
                nullptr
            ));
        }
        ARROW_RETURN_NOT_OK(builder->AppendValues(static_cast<int64_t>(num_elements), nullptr));

        return Error::ok();
    }
} // namespace rerun
