// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/lens_distortion.def.rs".

#pragma once

#include "../result.hpp"
#include "lens_distortion_model.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace rerun::encodings {
    /// **Encoding**: Parametric lens distortion of a pinhole camera, in OpenCV coefficient ordering.
    ///
    /// Describes how the real (distorted) lens deviates from the ideal linear pinhole projection.
    /// The coefficients apply to normalized camera coordinates, i.e. image coordinates
    /// after subtracting the principal point and dividing by the focal length.
    struct LensDistortion {
        /// Which parametric distortion model the coefficients belong to.
        rerun::encodings::LensDistortionModel model;

        /// Distortion coefficients `[k1, k2, p1, p2, k3, k4, k5, k6]` (OpenCV ordering).
        ///
        /// Models that use fewer coefficients leave the remaining entries at zero.
        std::array<double, 8> coefficients;

      public:
        LensDistortion() = default;
    };
} // namespace rerun::encodings

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<encodings::LensDistortion> {
        static constexpr std::string_view ComponentType = "rerun.encodings.LensDistortion";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::encodings::LensDistortion` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const encodings::LensDistortion* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const encodings::LensDistortion* elements,
            size_t num_elements
        );
    };
} // namespace rerun
