# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/encodings/lens_distortion_model.def.rs".

# You can extend this class by creating a "LensDistortionModelExt" class in "lens_distortion_model_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal

import pyarrow as pa

from .._baseclasses import (
    BaseBatch,
)

__all__ = ["LensDistortionModel", "LensDistortionModelArrayLike", "LensDistortionModelBatch", "LensDistortionModelLike"]


from enum import Enum


class LensDistortionModel(Enum):
    """
    **Encoding**: The parametric camera lens distortion model that a set of distortion coefficients belongs to.

    The model names and coefficient ordering follow the OpenCV calibration conventions,
    which are also used by ROS (`sensor_msgs/CameraInfo`).
    """

    PlumbBob = 1
    """
    Radial + tangential distortion ("Brown-Conrady"), known as `plumb_bob` in ROS.

    Uses the coefficients `k1, k2, p1, p2, k3` (the remaining coefficients are ignored / zero).
    """

    RationalPolynomial = 2
    """
    Rational polynomial distortion, known as `rational_polynomial` in ROS.

    Extends the plumb-bob model with a radial denominator polynomial, using all eight
    coefficients `k1, k2, p1, p2, k3, k4, k5, k6`.
    With `k4 = k5 = k6 = 0` this is identical to the plumb-bob model.
    """

    @classmethod
    def auto(cls, val: str | int | LensDistortionModel) -> LensDistortionModel:
        """Best-effort converter, including a case-insensitive string matcher."""
        if isinstance(val, LensDistortionModel):
            return val
        if isinstance(val, int):
            return cls(val)
        try:
            return cls[val]
        except KeyError:
            val_lower = val.lower()
            for variant in cls:
                if variant.name.lower() == val_lower:
                    return variant
        raise ValueError(f"Cannot convert {val} to {cls.__name__}")

    def __str__(self) -> str:
        """Returns the variant name."""
        return self.name


LensDistortionModelLike = (
    LensDistortionModel | Literal["PlumbBob", "RationalPolynomial", "plumbbob", "rationalpolynomial"] | int
)
"""A type alias for any LensDistortionModel-like object."""

LensDistortionModelArrayLike = (
    LensDistortionModel
    | Literal["PlumbBob", "RationalPolynomial", "plumbbob", "rationalpolynomial"]
    | int
    | Sequence[LensDistortionModelLike]
)
"""A type alias for any LensDistortionModel-like array object."""


class LensDistortionModelBatch(BaseBatch[LensDistortionModelArrayLike]):
    _ARROW_DATATYPE = pa.uint8()

    @staticmethod
    def _native_to_pa_array(data: LensDistortionModelArrayLike, data_type: pa.DataType) -> pa.Array:
        if isinstance(data, (LensDistortionModel, int, str)):
            data = [data]

        pa_data = [LensDistortionModel.auto(v).value if v is not None else None for v in data]  # type: ignore[redundant-expr]  # ty: ignore[not-iterable]

        return pa.array(pa_data, type=data_type)
