# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/encodings/lens_distortion.def.rs".

# You can extend this class by creating a "LensDistortionExt" class in "lens_distortion_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)
from .._converters import (
    to_np_float64,
)

if TYPE_CHECKING:
    import numpy as np
    import numpy.typing as npt

    from .. import encodings

__all__ = ["LensDistortion", "LensDistortionArrayLike", "LensDistortionBatch", "LensDistortionLike"]


@define(init=False)
class LensDistortion:
    """
    **Encoding**: Parametric lens distortion of a pinhole camera, in OpenCV coefficient ordering.

    Describes how the real (distorted) lens deviates from the ideal linear pinhole projection.
    The coefficients apply to normalized camera coordinates, i.e. image coordinates
    after subtracting the principal point and dividing by the focal length.
    """

    def __init__(self: Any, model: encodings.LensDistortionModelLike, coefficients: npt.ArrayLike) -> None:
        """
        Create a new instance of the LensDistortion encoding.

        Parameters
        ----------
        model:
            Which parametric distortion model the coefficients belong to.
        coefficients:
            Distortion coefficients `[k1, k2, p1, p2, k3, k4, k5, k6]` (OpenCV ordering).

            Models that use fewer coefficients leave the remaining entries at zero.

        """

        # You can define your own __init__ function as a member of LensDistortionExt in lens_distortion_ext.py
        self.__attrs_init__(model=model, coefficients=coefficients)

    model: encodings.LensDistortionModel = field()
    # Which parametric distortion model the coefficients belong to.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    coefficients: npt.NDArray[np.float64] = field(converter=to_np_float64)
    # Distortion coefficients `[k1, k2, p1, p2, k3, k4, k5, k6]` (OpenCV ordering).
    #
    # Models that use fewer coefficients leave the remaining entries at zero.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


LensDistortionLike = LensDistortion
"""A type alias for any LensDistortion-like object."""

LensDistortionArrayLike = LensDistortion | Sequence[LensDistortionLike]
"""A type alias for any LensDistortion-like array object."""


class LensDistortionBatch(BaseBatch[LensDistortionArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("model", pa.uint8(), nullable=False, metadata={}),
        pa.field(
            "coefficients",
            pa.list_(pa.field("item", pa.float64(), nullable=False, metadata={}), 8),
            nullable=False,
            metadata={},
        ),
    ])

    @staticmethod
    def _native_to_pa_array(data: LensDistortionArrayLike, data_type: pa.DataType) -> pa.Array:
        raise NotImplementedError(
            "Arrow serialization of LensDistortion not implemented: We lack codegen for arrow-serialization of general structs"
        )  # You need to implement native_to_pa_array_override in lens_distortion_ext.py
