// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/frozen_transform.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/transform_frame_id.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: Freezes the transform between two frames at a single point in time into a new, static frame.
    ///
    /// When logged, resolves the transform from `parent_frame` to `child_frame` at the time this
    /// archetype was logged, and connects the result as a fixed (non-propagating) edge from
    /// `parent_frame` to `frozen_frame`. Any transforms logged between `parent_frame` and
    /// `child_frame` after this point in time do not affect `frozen_frame`.
    ///
    /// If no transform relationship between `parent_frame` and `child_frame` can be resolved at the
    /// time this archetype was logged, `frozen_frame` falls back to an identity connection from
    /// `child_frame`.
    ///
    /// To learn more about transforms see [Spaces & Transforms](https://rerun.io/docs/concepts/spaces-and-transforms) in the reference.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct FrozenTransform {
        /// The frame to resolve the transform into.
        std::optional<ComponentBatch> parent_frame;

        /// The frame to resolve the transform from.
        std::optional<ComponentBatch> child_frame;

        /// The new, frozen frame that the resolved transform is connected to `parent_frame` under.
        std::optional<ComponentBatch> frozen_frame;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.FrozenTransform";

        /// `ComponentDescriptor` for the `parent_frame` field.
        static constexpr auto Descriptor_parent_frame = ComponentDescriptor(
            ArchetypeName, "FrozenTransform:parent_frame",
            Loggable<rerun::components::TransformFrameId>::ComponentType
        );
        /// `ComponentDescriptor` for the `child_frame` field.
        static constexpr auto Descriptor_child_frame = ComponentDescriptor(
            ArchetypeName, "FrozenTransform:child_frame",
            Loggable<rerun::components::TransformFrameId>::ComponentType
        );
        /// `ComponentDescriptor` for the `frozen_frame` field.
        static constexpr auto Descriptor_frozen_frame = ComponentDescriptor(
            ArchetypeName, "FrozenTransform:frozen_frame",
            Loggable<rerun::components::TransformFrameId>::ComponentType
        );

      public:
        FrozenTransform() = default;
        FrozenTransform(FrozenTransform&& other) = default;
        FrozenTransform(const FrozenTransform& other) = default;
        FrozenTransform& operator=(const FrozenTransform& other) = default;
        FrozenTransform& operator=(FrozenTransform&& other) = default;

        explicit FrozenTransform(
            rerun::components::TransformFrameId _parent_frame,
            rerun::components::TransformFrameId _child_frame,
            rerun::components::TransformFrameId _frozen_frame
        )
            : parent_frame(
                  ComponentBatch::from_loggable(std::move(_parent_frame), Descriptor_parent_frame)
                      .value_or_throw()
              ),
              child_frame(
                  ComponentBatch::from_loggable(std::move(_child_frame), Descriptor_child_frame)
                      .value_or_throw()
              ),
              frozen_frame(
                  ComponentBatch::from_loggable(std::move(_frozen_frame), Descriptor_frozen_frame)
                      .value_or_throw()
              ) {}

        /// Update only some specific fields of a `FrozenTransform`.
        static FrozenTransform update_fields() {
            return FrozenTransform();
        }

        /// Clear all the fields of a `FrozenTransform`.
        static FrozenTransform clear_fields();

        /// The frame to resolve the transform into.
        FrozenTransform with_parent_frame(const rerun::components::TransformFrameId& _parent_frame
        ) && {
            parent_frame = ComponentBatch::from_loggable(_parent_frame, Descriptor_parent_frame)
                               .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `parent_frame` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_parent_frame` should
        /// be used when logging a single row's worth of data.
        FrozenTransform with_many_parent_frame(
            const Collection<rerun::components::TransformFrameId>& _parent_frame
        ) && {
            parent_frame = ComponentBatch::from_loggable(_parent_frame, Descriptor_parent_frame)
                               .value_or_throw();
            return std::move(*this);
        }

        /// The frame to resolve the transform from.
        FrozenTransform with_child_frame(const rerun::components::TransformFrameId& _child_frame
        ) && {
            child_frame = ComponentBatch::from_loggable(_child_frame, Descriptor_child_frame)
                              .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `child_frame` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_child_frame` should
        /// be used when logging a single row's worth of data.
        FrozenTransform with_many_child_frame(
            const Collection<rerun::components::TransformFrameId>& _child_frame
        ) && {
            child_frame = ComponentBatch::from_loggable(_child_frame, Descriptor_child_frame)
                              .value_or_throw();
            return std::move(*this);
        }

        /// The new, frozen frame that the resolved transform is connected to `parent_frame` under.
        FrozenTransform with_frozen_frame(const rerun::components::TransformFrameId& _frozen_frame
        ) && {
            frozen_frame = ComponentBatch::from_loggable(_frozen_frame, Descriptor_frozen_frame)
                               .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `frozen_frame` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_frozen_frame` should
        /// be used when logging a single row's worth of data.
        FrozenTransform with_many_frozen_frame(
            const Collection<rerun::components::TransformFrameId>& _frozen_frame
        ) && {
            frozen_frame = ComponentBatch::from_loggable(_frozen_frame, Descriptor_frozen_frame)
                               .value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::FrozenTransform> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::FrozenTransform& archetype
        );
    };
} // namespace rerun
