// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/frozen_transform.fbs".

#include "frozen_transform.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    FrozenTransform FrozenTransform::clear_fields() {
        auto archetype = FrozenTransform();
        archetype.parent_frame =
            ComponentBatch::empty<rerun::components::TransformFrameId>(Descriptor_parent_frame)
                .value_or_throw();
        archetype.child_frame =
            ComponentBatch::empty<rerun::components::TransformFrameId>(Descriptor_child_frame)
                .value_or_throw();
        archetype.frozen_frame =
            ComponentBatch::empty<rerun::components::TransformFrameId>(Descriptor_frozen_frame)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> FrozenTransform::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(3);
        if (parent_frame.has_value()) {
            columns.push_back(parent_frame.value().partitioned(lengths_).value_or_throw());
        }
        if (child_frame.has_value()) {
            columns.push_back(child_frame.value().partitioned(lengths_).value_or_throw());
        }
        if (frozen_frame.has_value()) {
            columns.push_back(frozen_frame.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> FrozenTransform::columns() {
        if (parent_frame.has_value()) {
            return columns(std::vector<uint32_t>(parent_frame.value().length(), 1));
        }
        if (child_frame.has_value()) {
            return columns(std::vector<uint32_t>(child_frame.value().length(), 1));
        }
        if (frozen_frame.has_value()) {
            return columns(std::vector<uint32_t>(frozen_frame.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::FrozenTransform>::as_batches(
        const archetypes::FrozenTransform& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(3);

        if (archetype.parent_frame.has_value()) {
            cells.push_back(archetype.parent_frame.value());
        }
        if (archetype.child_frame.has_value()) {
            cells.push_back(archetype.child_frame.value());
        }
        if (archetype.frozen_frame.has_value()) {
            cells.push_back(archetype.frozen_frame.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
