# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/components/lens_distortion.def.rs".

# You can extend this class by creating a "LensDistortionExt" class in "lens_distortion_ext.py".

from __future__ import annotations

from .. import encodings
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["LensDistortion", "LensDistortionBatch"]


class LensDistortion(encodings.LensDistortion, ComponentMixin):
    """
    **Component**: Parametric lens distortion of a pinhole camera, in OpenCV coefficient ordering.

    When attached to a [`archetypes.Pinhole`][rerun.archetypes.Pinhole], the viewer rectifies (undistorts) images
    shown under that camera so that the linear `image_from_camera` projection maps
    3D geometry onto the correct pixels.
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of LensDistortionExt in lens_distortion_ext.py

    # Note: there are no fields here because LensDistortion delegates to encodings.LensDistortion


class LensDistortionBatch(encodings.LensDistortionBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.LensDistortion"


# This is patched in late to avoid circular dependencies.
LensDistortion._BATCH_TYPE = LensDistortionBatch  # type: ignore[assignment]
