# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/frozen_transform.fbs".

# You can extend this class by creating a "FrozenTransformExt" class in "frozen_transform_ext.py".

from __future__ import annotations

from typing import Any, ClassVar

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
    ComponentDescriptor,
)
from ..error_utils import catch_and_log_exceptions

__all__ = ["FrozenTransform"]


@define(str=False, repr=False, init=False)
class FrozenTransform(Archetype):
    """
    **Archetype**: Freezes the transform between two frames at a single point in time into a new, static frame.

    When logged, resolves the transform from `parent_frame` to `child_frame` at the time this
    archetype was logged, and connects the result as a fixed (non-propagating) edge from
    `parent_frame` to `frozen_frame`. Any transforms logged between `parent_frame` and
    `child_frame` after this point in time do not affect `frozen_frame`.

    If no transform relationship between `parent_frame` and `child_frame` can be resolved at the
    time this archetype was logged, `frozen_frame` falls back to an identity connection from
    `child_frame`.

    To learn more about transforms see [Spaces & Transforms](https://rerun.io/docs/concepts/spaces-and-transforms) in the reference.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    NAME: ClassVar[str] = "rerun.archetypes.FrozenTransform"

    def __init__(
        self: Any,
        *,
        parent_frame: datatypes.Utf8Like,
        child_frame: datatypes.Utf8Like,
        frozen_frame: datatypes.Utf8Like,
    ) -> None:
        """
        Create a new instance of the FrozenTransform archetype.

        Parameters
        ----------
        parent_frame:
            The frame to resolve the transform into.
        child_frame:
            The frame to resolve the transform from.
        frozen_frame:
            The new, frozen frame that the resolved transform is connected to `parent_frame` under.

        """

        # You can define your own __init__ function as a member of FrozenTransformExt in frozen_transform_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(parent_frame=parent_frame, child_frame=child_frame, frozen_frame=frozen_frame)
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            parent_frame=None,
            child_frame=None,
            frozen_frame=None,
        )

    @classmethod
    def _clear(cls) -> FrozenTransform:
        """Produce an empty FrozenTransform, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        parent_frame: datatypes.Utf8Like | None = None,
        child_frame: datatypes.Utf8Like | None = None,
        frozen_frame: datatypes.Utf8Like | None = None,
    ) -> FrozenTransform:
        """
        Update only some specific fields of a `FrozenTransform`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        parent_frame:
            The frame to resolve the transform into.
        child_frame:
            The frame to resolve the transform from.
        frozen_frame:
            The new, frozen frame that the resolved transform is connected to `parent_frame` under.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "parent_frame": parent_frame,
                "child_frame": child_frame,
                "frozen_frame": frozen_frame,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> FrozenTransform:
        """Clear all the fields of a `FrozenTransform`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_parent_frame() -> ComponentDescriptor:
        return ComponentDescriptor(
            "FrozenTransform:parent_frame",
            archetype=FrozenTransform.NAME,
            component_type=components.TransformFrameIdBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_child_frame() -> ComponentDescriptor:
        return ComponentDescriptor(
            "FrozenTransform:child_frame",
            archetype=FrozenTransform.NAME,
            component_type=components.TransformFrameIdBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_frozen_frame() -> ComponentDescriptor:
        return ComponentDescriptor(
            "FrozenTransform:frozen_frame",
            archetype=FrozenTransform.NAME,
            component_type=components.TransformFrameIdBatch._COMPONENT_TYPE,
        )

    @classmethod
    def columns(
        cls,
        *,
        parent_frame: datatypes.Utf8ArrayLike | None = None,
        child_frame: datatypes.Utf8ArrayLike | None = None,
        frozen_frame: datatypes.Utf8ArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        parent_frame:
            The frame to resolve the transform into.
        child_frame:
            The frame to resolve the transform from.
        frozen_frame:
            The new, frozen frame that the resolved transform is connected to `parent_frame` under.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                parent_frame=parent_frame,
                child_frame=child_frame,
                frozen_frame=frozen_frame,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "FrozenTransform:parent_frame": parent_frame,
            "FrozenTransform:child_frame": child_frame,
            "FrozenTransform:frozen_frame": frozen_frame,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type):
                    elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                    if arrow_array.type.list_size == elem_flat_len:
                        # The product of the last dimensions of the shape are equal to the size of the fixed size list array,
                        # so we have `num_rows` single element batches (each element is a fixed sized list).
                        batch_length = 1
                    else:
                        batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                else:
                    # For primitive types, derive batch_length from the actual arrow array length
                    # since the input shape can be misleading (e.g. colors [R,G,B] -> single uint32).
                    batch_length = len(arrow_array) // num_rows if num_rows > 0 else 1

                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    parent_frame: components.TransformFrameIdBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TransformFrameIdBatch._converter,  # type: ignore[misc]
    )
    # The frame to resolve the transform into.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    child_frame: components.TransformFrameIdBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TransformFrameIdBatch._converter,  # type: ignore[misc]
    )
    # The frame to resolve the transform from.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    frozen_frame: components.TransformFrameIdBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TransformFrameIdBatch._converter,  # type: ignore[misc]
    )
    # The new, frozen frame that the resolved transform is connected to `parent_frame` under.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]
