// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/blueprint/components/follow_delay_ms.def.rs".

#pragma once

#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class UInt64Type;
    using UInt64Builder = NumericBuilder<UInt64Type>;
} // namespace arrow

namespace rerun::blueprint::components {
    /// **Component**: Add delay in follow mode to allow proper buffering.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct FollowDelayMs {
        uint64_t delay;

      public:
        FollowDelayMs() = default;

        FollowDelayMs(uint64_t delay_) : delay(delay_) {}

        FollowDelayMs& operator=(uint64_t delay_) {
            delay = delay_;
            return *this;
        }
    };
} // namespace rerun::blueprint::components

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<blueprint::components::FollowDelayMs> {
        static constexpr std::string_view ComponentType =
            "rerun.blueprint.components.FollowDelayMs";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::blueprint:: components::FollowDelayMs` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::FollowDelayMs* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::UInt64Builder* builder, const blueprint::components::FollowDelayMs* elements,
            size_t num_elements
        );
    };
} // namespace rerun
