// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/frozen_transform.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: Freezes the transform between two frames at a single point in time into a new, static frame.
///
/// When logged, resolves the transform from `parent_frame` to `child_frame` at the time this
/// archetype was logged, and connects the result as a fixed (non-propagating) edge from
/// `parent_frame` to `frozen_frame`. Any transforms logged between `parent_frame` and
/// `child_frame` after this point in time do not affect `frozen_frame`.
///
/// If no transform relationship between `parent_frame` and `child_frame` can be resolved at the
/// time this archetype was logged, `frozen_frame` falls back to an identity connection from
/// `child_frame`.
///
/// To learn more about transforms see [Spaces & Transforms](https://rerun.io/docs/concepts/spaces-and-transforms) in the reference.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, Default, ::re_byte_size::SizeBytes)]
pub struct FrozenTransform {
    /// The frame to resolve the transform into.
    pub parent_frame: Option<SerializedComponentBatch>,

    /// The frame to resolve the transform from.
    pub child_frame: Option<SerializedComponentBatch>,

    /// The new, frozen frame that the resolved transform is connected to `parent_frame` under.
    pub frozen_frame: Option<SerializedComponentBatch>,
}

impl FrozenTransform {
    /// Returns the [`ComponentDescriptor`] for [`Self::parent_frame`].
    ///
    /// The corresponding component is [`crate::components::TransformFrameId`].
    #[inline]
    pub fn descriptor_parent_frame() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.FrozenTransform".into()),
                component: "FrozenTransform:parent_frame".into(),
                component_type: Some("rerun.components.TransformFrameId".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::child_frame`].
    ///
    /// The corresponding component is [`crate::components::TransformFrameId`].
    #[inline]
    pub fn descriptor_child_frame() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.FrozenTransform".into()),
                component: "FrozenTransform:child_frame".into(),
                component_type: Some("rerun.components.TransformFrameId".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::frozen_frame`].
    ///
    /// The corresponding component is [`crate::components::TransformFrameId`].
    #[inline]
    pub fn descriptor_frozen_frame() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.FrozenTransform".into()),
                component: "FrozenTransform:frozen_frame".into(),
                component_type: Some("rerun.components.TransformFrameId".into()),
            });
        (*DESCRIPTOR).clone()
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            FrozenTransform::descriptor_parent_frame(),
            FrozenTransform::descriptor_child_frame(),
            FrozenTransform::descriptor_frozen_frame(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            FrozenTransform::descriptor_parent_frame(),
            FrozenTransform::descriptor_child_frame(),
            FrozenTransform::descriptor_frozen_frame(),
        ]
    });

impl FrozenTransform {
    /// The total number of components in the archetype: 3 required, 0 recommended, 0 optional
    pub const NUM_COMPONENTS: usize = 3usize;
}

impl ::re_types_core::Archetype for FrozenTransform {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        ::re_types_core::external::re_string_interner::intern_static_nonempty!(
            ::re_types_core::ArchetypeName,
            "rerun.archetypes.FrozenTransform"
        )
    }

    #[inline]
    fn display_name() -> &'static str {
        "Frozen transform"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let parent_frame = arrays_by_descr
            .get(&Self::descriptor_parent_frame())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_parent_frame())
            });
        let child_frame = arrays_by_descr
            .get(&Self::descriptor_child_frame())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_child_frame())
            });
        let frozen_frame = arrays_by_descr
            .get(&Self::descriptor_frozen_frame())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_frozen_frame())
            });
        Ok(Self {
            parent_frame,
            child_frame,
            frozen_frame,
        })
    }
}

impl ::re_types_core::AsComponents for FrozenTransform {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.parent_frame.clone(),
            self.child_frame.clone(),
            self.frozen_frame.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for FrozenTransform {}

impl FrozenTransform {
    /// Create a new `FrozenTransform`.
    #[inline]
    pub fn new(
        parent_frame: impl Into<crate::components::TransformFrameId>,
        child_frame: impl Into<crate::components::TransformFrameId>,
        frozen_frame: impl Into<crate::components::TransformFrameId>,
    ) -> Self {
        Self {
            parent_frame: try_serialize_field(Self::descriptor_parent_frame(), [parent_frame]),
            child_frame: try_serialize_field(Self::descriptor_child_frame(), [child_frame]),
            frozen_frame: try_serialize_field(Self::descriptor_frozen_frame(), [frozen_frame]),
        }
    }

    /// Update only some specific fields of a `FrozenTransform`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `FrozenTransform`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            parent_frame: Some(SerializedComponentBatch::new(
                crate::components::TransformFrameId::arrow_empty(),
                Self::descriptor_parent_frame(),
            )),
            child_frame: Some(SerializedComponentBatch::new(
                crate::components::TransformFrameId::arrow_empty(),
                Self::descriptor_child_frame(),
            )),
            frozen_frame: Some(SerializedComponentBatch::new(
                crate::components::TransformFrameId::arrow_empty(),
                Self::descriptor_frozen_frame(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.parent_frame
                .map(|parent_frame| parent_frame.partitioned(_lengths.clone()))
                .transpose()?,
            self.child_frame
                .map(|child_frame| child_frame.partitioned(_lengths.clone()))
                .transpose()?,
            self.frozen_frame
                .map(|frozen_frame| frozen_frame.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_parent_frame = self.parent_frame.as_ref().map(|b| b.array.len());
        let len_child_frame = self.child_frame.as_ref().map(|b| b.array.len());
        let len_frozen_frame = self.frozen_frame.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_parent_frame)
            .or(len_child_frame)
            .or(len_frozen_frame)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// The frame to resolve the transform into.
    #[inline]
    pub fn with_parent_frame(
        mut self,
        parent_frame: impl Into<crate::components::TransformFrameId>,
    ) -> Self {
        self.parent_frame = try_serialize_field(Self::descriptor_parent_frame(), [parent_frame]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::TransformFrameId`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_parent_frame`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_parent_frame(
        mut self,
        parent_frame: impl IntoIterator<Item = impl Into<crate::components::TransformFrameId>>,
    ) -> Self {
        self.parent_frame = try_serialize_field(Self::descriptor_parent_frame(), parent_frame);
        self
    }

    /// The frame to resolve the transform from.
    #[inline]
    pub fn with_child_frame(
        mut self,
        child_frame: impl Into<crate::components::TransformFrameId>,
    ) -> Self {
        self.child_frame = try_serialize_field(Self::descriptor_child_frame(), [child_frame]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::TransformFrameId`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_child_frame`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_child_frame(
        mut self,
        child_frame: impl IntoIterator<Item = impl Into<crate::components::TransformFrameId>>,
    ) -> Self {
        self.child_frame = try_serialize_field(Self::descriptor_child_frame(), child_frame);
        self
    }

    /// The new, frozen frame that the resolved transform is connected to `parent_frame` under.
    #[inline]
    pub fn with_frozen_frame(
        mut self,
        frozen_frame: impl Into<crate::components::TransformFrameId>,
    ) -> Self {
        self.frozen_frame = try_serialize_field(Self::descriptor_frozen_frame(), [frozen_frame]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::TransformFrameId`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_frozen_frame`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_frozen_frame(
        mut self,
        frozen_frame: impl IntoIterator<Item = impl Into<crate::components::TransformFrameId>>,
    ) -> Self {
        self.frozen_frame = try_serialize_field(Self::descriptor_frozen_frame(), frozen_frame);
        self
    }
}
