// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/lens_distortion.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Encoding**: Parametric lens distortion of a pinhole camera, in OpenCV coefficient ordering.
///
/// Describes how the real (distorted) lens deviates from the ideal linear pinhole projection.
/// The coefficients apply to normalized camera coordinates, i.e. image coordinates
/// after subtracting the principal point and dividing by the focal length.
#[derive(Clone, Debug, Copy, PartialEq, ::re_byte_size::SizeBytes)]
pub struct LensDistortion {
    /// Which parametric distortion model the coefficients belong to.
    pub model: crate::encodings::LensDistortionModel,

    /// Distortion coefficients `[k1, k2, p1, p2, k3, k4, k5, k6]` (OpenCV ordering).
    ///
    /// Models that use fewer coefficients leave the remaining entries at zero.
    pub coefficients: [f64; 8usize],
}

::re_types_core::macros::impl_into_cow!(LensDistortion);

impl ::re_types_core::ArrowDataType for LensDistortion {
    #[inline]
    fn arrow_data_type() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::Struct(Fields::from(vec![
            Field::new(
                "model",
                <crate::encodings::LensDistortionModel>::arrow_data_type(),
                false,
            ),
            Field::new(
                "coefficients",
                DataType::FixedSizeList(
                    std::sync::Arc::new(Field::new("item", DataType::Float64, false)),
                    8,
                ),
                false,
            ),
        ]))
    }
}

impl ::re_types_core::ToArrow for LensDistortion {
    fn to_arrow<'a>(
        data: impl IntoIterator<Item = impl Into<Cow<'a, Self>>>,
    ) -> SerializationResult<ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{
            ArrowDataType as _, ResultExt as _, ToArrow as _, ToArrowOpt as _,
            arrow_helpers::as_array_ref,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let fields = Fields::from(vec![
                Field::new(
                    "model",
                    <crate::encodings::LensDistortionModel>::arrow_data_type(),
                    false,
                ),
                Field::new(
                    "coefficients",
                    DataType::FixedSizeList(
                        std::sync::Arc::new(Field::new("item", DataType::Float64, false)),
                        8,
                    ),
                    false,
                ),
            ]);
            let data: Vec<_> = data
                .into_iter()
                .map(|datum| {
                    let datum: Cow<'a, Self> = datum.into();
                    datum
                })
                .collect();
            let validity = None;
            as_array_ref(StructArray::new(
                fields,
                vec![
                    {
                        let (somes, model): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.model.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let model_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let _ = model_validity;
                            crate::encodings::LensDistortionModel::to_arrow_opt(model)?
                        }
                    },
                    {
                        let (somes, coefficients): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.coefficients.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let coefficients_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let coefficients_inner_data: Vec<_> = coefficients
                                .into_iter()
                                .flat_map(|v| match v {
                                    Some(v) => itertools::Either::Left(v.into_iter()),
                                    None => itertools::Either::Right(std::iter::repeat_n(
                                        Default::default(),
                                        8usize,
                                    )),
                                })
                                .collect();
                            let coefficients_inner_validity: Option<arrow::buffer::NullBuffer> =
                                coefficients_validity.as_ref().map(|validity| {
                                    validity
                                        .iter()
                                        .map(|b| std::iter::repeat_n(b, 8usize))
                                        .flatten()
                                        .collect::<Vec<_>>()
                                        .into()
                                });
                            as_array_ref(FixedSizeListArray::new(
                                std::sync::Arc::new(Field::new("item", DataType::Float64, false)),
                                8,
                                as_array_ref(PrimitiveArray::<Float64Type>::new(
                                    coefficients_inner_data.into_iter().collect(),
                                    coefficients_inner_validity,
                                )),
                                coefficients_validity,
                            ))
                        }
                    },
                ],
                validity,
            ))
        })
    }
}

impl ::re_types_core::FromArrow for LensDistortion {
    fn from_arrow(arrow_data: &dyn arrow::array::Array) -> DeserializationResult<Vec<Self>> {
        use ::re_types_core::{
            ArrowDataType as _, FromArrow as _, FromArrowOpt as _, ResultExt as _,
            arrow_helpers::*, arrow_zip_validity::ZipValidity,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        err_on_nulls(arrow_data, "rerun.encodings.LensDistortion")?;
        Ok({
            {
                let arrow_data = arrow_data
                    .try_cast::<arrow::array::StructArray>(|| Self::arrow_data_type())
                    .with_context("rerun.encodings.LensDistortion")?;
                if arrow_data.is_empty() {
                    Vec::new()
                } else {
                    let (arrow_data_fields, arrow_data_arrays) =
                        (arrow_data.fields(), arrow_data.columns());
                    let arrays_by_name: ::std::collections::HashMap<_, _> = ::std::iter::zip(
                        arrow_data_fields.iter().map(|field| field.name().as_str()),
                        arrow_data_arrays,
                    )
                    .collect();
                    let model = {
                        if !arrays_by_name.contains_key("model") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "model",
                            ))
                            .with_context("rerun.encodings.LensDistortion");
                        }
                        let arrow_data = &**arrays_by_name["model"];
                        crate::encodings::LensDistortionModel::from_arrow_opt(arrow_data)
                            .with_context("rerun.encodings.LensDistortion#model")?
                            .into_iter()
                    };
                    let coefficients = {
                        if !arrays_by_name.contains_key("coefficients") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "coefficients",
                            ))
                            .with_context("rerun.encodings.LensDistortion");
                        }
                        let arrow_data = &**arrays_by_name["coefficients"];
                        {
                            let arrow_data = arrow_data
                                .try_cast::<arrow::array::FixedSizeListArray>(|| {
                                    DataType::FixedSizeList(
                                        std::sync::Arc::new(Field::new(
                                            "item",
                                            DataType::Float64,
                                            false,
                                        )),
                                        8,
                                    )
                                })
                                .with_context("rerun.encodings.LensDistortion#coefficients")?;
                            if arrow_data.is_empty() {
                                Vec::new()
                            } else {
                                let offsets = ::std::iter::zip(
                                    (0..).step_by(8usize),
                                    (8usize..).step_by(8usize).take(arrow_data.len()),
                                );
                                let arrow_data_inner = {
                                    let arrow_data_inner = &**arrow_data.values();
                                    arrow_data_inner
                                        .try_cast::<Float64Array>(|| DataType::Float64)
                                        .with_context(
                                            "rerun.encodings.LensDistortion#coefficients",
                                        )?
                                        .into_iter()
                                        .collect::<Vec<_>>()
                                };
                                ZipValidity::new_with_validity(offsets, arrow_data.nulls())
                                    .map(|elem| {
                                        elem.map(|(start, end): (usize, usize)| {
                                            re_log::debug_assert!(end - start == 8usize);
                                            if arrow_data_inner.len() < end {
                                                return Err(
                                                    DeserializationError::offset_slice_oob(
                                                        (start, end),
                                                        arrow_data_inner.len(),
                                                    ),
                                                );
                                            }

                                            #[expect(
                                                unsafe_code,
                                                clippy::undocumented_unsafe_blocks
                                            )]
                                            let data = unsafe {
                                                arrow_data_inner.get_unchecked(start..end)
                                            };
                                            let data =
                                                data.iter().cloned().map(Option::unwrap_or_default);

                                            // NOTE: Unwrapping cannot fail: the length must be correct.
                                            #[expect(clippy::unwrap_used)]
                                            Ok(array_init::from_iter(data).unwrap())
                                        })
                                        .transpose()
                                    })
                                    .collect::<DeserializationResult<Vec<Option<_>>>>()?
                            }
                            .into_iter()
                        }
                    };
                    ZipValidity::new_with_validity(
                        ::itertools::izip!(model, coefficients),
                        arrow_data.nulls(),
                    )
                    .map(|opt| {
                        opt.map(|(model, coefficients)| {
                            Ok(Self {
                                model: model
                                    .ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.encodings.LensDistortion#model")?,
                                coefficients: coefficients
                                    .ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.encodings.LensDistortion#coefficients")?,
                            })
                        })
                        .transpose()
                    })
                    .collect::<DeserializationResult<Vec<_>>>()
                    .with_context("rerun.encodings.LensDistortion")?
                }
            }
        }
        .into_iter()
        .map(|v| v.ok_or_else(DeserializationError::missing_data))
        .collect::<DeserializationResult<Vec<_>>>()?)
    }
}
