// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/lens_distortion_model.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]
#![allow(non_camel_case_types)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Encoding**: The parametric camera lens distortion model that a set of distortion coefficients belongs to.
///
/// The model names and coefficient ordering follow the OpenCV calibration conventions,
/// which are also used by ROS (`sensor_msgs/CameraInfo`).
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq, Default, ::re_byte_size::SizeBytes)]
#[repr(u8)]
pub enum LensDistortionModel {
    /// Radial + tangential distortion ("Brown-Conrady"), known as `plumb_bob` in ROS.
    ///
    /// Uses the coefficients `k1, k2, p1, p2, k3` (the remaining coefficients are ignored / zero).
    #[default]
    PlumbBob = 1,

    /// Rational polynomial distortion, known as `rational_polynomial` in ROS.
    ///
    /// Extends the plumb-bob model with a radial denominator polynomial, using all eight
    /// coefficients `k1, k2, p1, p2, k3, k4, k5, k6`.
    /// With `k4 = k5 = k6 = 0` this is identical to the plumb-bob model.
    RationalPolynomial = 2,
}

::re_types_core::macros::impl_into_cow!(LensDistortionModel);

impl ::re_types_core::ArrowDataType for LensDistortionModel {
    #[inline]
    fn arrow_data_type() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::UInt8
    }
}

impl ::re_types_core::ToArrowOpt for LensDistortionModel {
    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<Cow<'a, Self>>>>,
    ) -> SerializationResult<ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{
            ArrowDataType as _, ResultExt as _, ToArrow as _, ToArrowOpt as _,
            arrow_helpers::as_array_ref,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let (somes, data0): (Vec<_>, Vec<_>) = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<Cow<'a, Self>> = datum.map(Into::into);
                    let datum = datum.map(|datum| *datum as u8);
                    (datum.is_some(), datum)
                })
                .unzip();
            let data0_validity: Option<arrow::buffer::NullBuffer> = {
                let any_nones = somes.iter().any(|some| !*some);
                any_nones.then(|| somes.into())
            };
            as_array_ref(PrimitiveArray::<UInt8Type>::new(
                data0.into_iter().map(|v| v.unwrap_or_default()).collect(),
                data0_validity,
            ))
        })
    }
}

::re_types_core::macros::impl_to_arrow_via_to_arrow_opt!(LensDistortionModel);

impl ::re_types_core::FromArrowOpt for LensDistortionModel {
    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>> {
        use ::re_types_core::{
            ArrowDataType as _, FromArrow as _, FromArrowOpt as _, ResultExt as _,
            arrow_helpers::*, arrow_zip_validity::ZipValidity,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok(arrow_data
            .try_cast::<UInt8Array>(|| Self::arrow_data_type())
            .with_context("rerun.encodings.LensDistortionModel#enum")?
            .into_iter()
            .map(|typ| match typ {
                Some(val) => <Self as ::re_types_core::reflection::Enum>::try_from_integer(val)
                    .map(Some)
                    .ok_or_else(|| {
                        DeserializationError::missing_union_arm(
                            Self::arrow_data_type(),
                            "<invalid>",
                            val as _,
                        )
                    }),
                None => Ok(None),
            })
            .collect::<DeserializationResult<Vec<_>>>()
            .with_context("rerun.encodings.LensDistortionModel")?)
    }
}

::re_types_core::macros::impl_from_arrow_via_from_arrow_opt!(LensDistortionModel);

impl std::fmt::Display for LensDistortionModel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::PlumbBob => write!(f, "PlumbBob"),
            Self::RationalPolynomial => write!(f, "RationalPolynomial"),
        }
    }
}

impl ::re_types_core::reflection::Enum for LensDistortionModel {
    type Repr = u8;

    #[inline]
    fn variants() -> &'static [Self] {
        &[Self::PlumbBob, Self::RationalPolynomial]
    }

    #[inline]
    fn docstring_md(self) -> &'static str {
        match self {
            Self::PlumbBob => {
                "Radial + tangential distortion (\"Brown-Conrady\"), known as `plumb_bob` in ROS.\n\nUses the coefficients `k1, k2, p1, p2, k3` (the remaining coefficients are ignored / zero)."
            }
            Self::RationalPolynomial => {
                "Rational polynomial distortion, known as `rational_polynomial` in ROS.\n\nExtends the plumb-bob model with a radial denominator polynomial, using all eight\ncoefficients `k1, k2, p1, p2, k3, k4, k5, k6`.\nWith `k4 = k5 = k6 = 0` this is identical to the plumb-bob model."
            }
        }
    }

    #[inline]
    fn try_from_integer(value: u8) -> Option<Self> {
        Self::variants()
            .get((value as usize).wrapping_sub(1))
            .copied()
    }
}
